// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxqDM-YkkX8TAXQAmbigz-f9LNMh0LGfI',
    appId: '1:805911421419:web:aa0e7098a169db81b1f9ae',
    messagingSenderId: '805911421419',
    projectId: 'taskmate-b9844',
    authDomain: 'taskmate-b9844.firebaseapp.com',
    storageBucket: 'taskmate-b9844.firebasestorage.app',
    measurementId: 'G-MBCL72F215',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPEcpyE2BRCiYt3Ech8U1YBKnC6OSAHuk',
    appId: '1:805911421419:android:3f54f265a00e02d8b1f9ae',
    messagingSenderId: '805911421419',
    projectId: 'taskmate-b9844',
    storageBucket: 'taskmate-b9844.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzuS8tRnsK6dzwyWhC3Ai97Q1Py4x3RY0',
    appId: '1:805911421419:ios:30edb36204944f81b1f9ae',
    messagingSenderId: '805911421419',
    projectId: 'taskmate-b9844',
    storageBucket: 'taskmate-b9844.firebasestorage.app',
    iosClientId: '805911421419-efrsh7mj0od6feo002imo55muhenv489.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzuS8tRnsK6dzwyWhC3Ai97Q1Py4x3RY0',
    appId: '1:805911421419:ios:30edb36204944f81b1f9ae',
    messagingSenderId: '805911421419',
    projectId: 'taskmate-b9844',
    storageBucket: 'taskmate-b9844.firebasestorage.app',
    iosClientId: '805911421419-efrsh7mj0od6feo002imo55muhenv489.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxqDM-YkkX8TAXQAmbigz-f9LNMh0LGfI',
    appId: '1:805911421419:web:692e460cd2a90468b1f9ae',
    messagingSenderId: '805911421419',
    projectId: 'taskmate-b9844',
    authDomain: 'taskmate-b9844.firebaseapp.com',
    storageBucket: 'taskmate-b9844.firebasestorage.app',
    measurementId: 'G-7G5695W9XB',
  );
}
